version: "3.8"
services:
  php:
    image: ritthikrairw/wordpress-bedrock:${PHP_VERSION:?php7.4-fpm}
    container_name: ${APP_NAME:?wordpress}-php
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - "${APP_ROOT}/.env:/var/www/html/.env"
      - "${APP_ROOT}/public:/var/www/html"
      - "${APP_ROOT}/shared/uploads:/var/www/html/web/app/uploads"
      - "${APP_ROOT}/system/conf/php/custom.ini:/usr/local/etc/php/conf.d/uploads.ini:rw,delegated"
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
    networks:
      - webserver-network
      - database-network

  nginx:
    image: nginx:1.20-alpine
    container_name: ${APP_NAME:?wordpress}-nginx
    environment:
      NGINX_SERVER_NAME: ${NGINX_SERVER_NAME:?localhost}
    restart: unless-stopped
    links:
      - php
    volumes:
      - "${APP_ROOT}/.env:/var/www/html/.env"
      - "${APP_ROOT}/public:/var/www/html"
      - "${APP_ROOT}/shared/uploads:/var/www/html/web/app/uploads"
      - "${APP_ROOT}/system/conf/nginx/includes:/etc/nginx/includes"
      - "${APP_ROOT}/shared/ssl:/etc/nginx/ssl"
      - "${APP_ROOT}/system/conf/nginx/templates/${NGINX_SITE_CONFIG:?site.conf.template}:/etc/nginx/templates/default.conf.template"
      - "${APP_ROOT}/system/conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "${APP_ROOT}/system/logs/nginx:/var/log/nginx:rw"
    networks:
      - proxy
      - webserver-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.${APP_NAME}-nginx.rule=Host(`${NGINX_SERVER_NAME}`)"
      - "traefik.http.routers.${APP_NAME}-nginx.tls=true"
      - "traefik.http.routers.${APP_NAME}-nginx.entrypoints=websecure"
      # - "traefik.http.routers.${APP_NAME}-nginx.tls.certresolver=myresolver"
      - "traefik.http.routers.${APP_NAME}-nginx.service=${APP_NAME}-nginx"
      - "traefik.http.services.${APP_NAME}-nginx.loadbalancer.server.port=80"

  mariadb:
    image: mariadb:10.5
    container_name: ${APP_NAME:?wordpress}-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?1234}
      MYSQL_DATABASE: ${DB_NAME:?wordpress_db}
      MYSQL_USER: ${DB_USER:?wordpress_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:?password}
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - database-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ${APP_NAME:?wordpress}-phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
    volumes:
      - "${APP_ROOT}/system/conf/php/custom.ini:/usr/local/etc/php/conf.d/uploads.ini:rw,delegated"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.${APP_NAME}-phpmyadmin.rule=Host(`${PHPMYADMIN_HOST_NAME}`)"
      - "traefik.http.routers.${APP_NAME}-phpmyadmin.tls=true"
      # - "traefik.http.routers.${APP_NAME}-phpmyadmin.tls.certresolver=myresolver"
      - "traefik.http.routers.${APP_NAME}-phpmyadmin.entrypoints=websecure"
    networks:
      - proxy
      - database-network

volumes:
  mariadb-data:
    name: ${APP_NAME:?wordpress}-mariadb-data

networks:
  webserver-network:
    driver: bridge
  database-network:
    driver: bridge
  proxy:
    external: true
